### ISSUE TITLE
Create footer for webpage

### ISSUE THREAD

**Issue by overeha** [code4romania/whos-who#10]
The footer should display the standard branding and useful links area
The useful links area will display: 

COLUMN 1
- Despre proiect 
- Guvernul Romaniei
- Departamentul pentru Situații de Urgență
- Ministerul Sanatatii 

COLUMN 2
- Știri oficiale
- Ce trebuie să fac
- Date la zi
- RoHelp
- Code for Romania

background color: #00478F

**Comment by aniri** [comment]
Please reuse component from https://taskforce-fe-components.now.sh/?path=/story/footer--with-more-columns

**Comment by Anca07** [comment]
Hi! I would like to work on this issue :)

**Comment by tudoramariei** [comment]
Sure, Anca! It's yours!
