### ISSUE TITLE
Add social og tags

### ISSUE THREAD

**Issue by overeha** [code4romania/whos-who#11]
Tags:

- [ ]  og:url
- [ ]  og:type = website
- [ ]  og:title (the title of the page. In case of a need form will be the title of the need )
- [ ]  og:description
- [ ]  og:image

**Comment by GabrielMajeri** [comment]
I want to work on this :v:

**Comment by GabrielMajeri** [comment]
I've checked out the code locally, the site already has `og` tags:

https://github.com/code4romania/whos-who/blob/39ad22f9c9f856625ee6c7fc4783319bcae9a258/public/index.html#L13-L20

I'm guessing I should add on a per-route basis using something like [react-helmet](https://github.com/nfl/react-helmet)? If so, what info should I change for each component?

**Comment by tudoramariei** [comment]
I'm not sure what to say here so I'll ask for a second opinion 
@overeha @catileptic @aniri @RaduCStefanescu 
What do you think? Should we implement a per-page description? Have the content of the preview change depending on the shared page 🤔

**Comment by overeha** [comment]
It's a good idea. I will get back with distinct descriptions

**Comment by GabrielMajeri** [comment]
I've started working on this and hit an issue.

If we update the description using JavaScript, the social media preview wouldn't be updated, so it would be all for nothing. 

The solution would be to use [Server-Side Rendering](https://github.com/nfl/react-helmet/issues/26) (unless it's configured already?) to get the crawler to read the updated descriptions.

**Comment by tudoramariei** [comment]
I will be closing this for now and continue the discussion on a different issue
