### ISSUE TITLE
Adapt Main Navigation

### ISSUE THREAD

**Issue by overeha** [code4romania/whos-who#13]
The main navigation has four tabs as shown below the graph embed area. 

![Homepage](https://user-images.githubusercontent.com/45068169/77808614-be654500-7094-11ea-87f9-a4fae35fe84e.png)

**Comment by aniri** [comment]
Please reuse componets from https://taskforce-fe-components.now.sh/?path=/story/list--three-column-list

**Comment by teodoradima** [comment]
I'll take this one 🙋‍♀️

**Comment by tudoramariei** [comment]
Sure, Teo! It's all yours!
