### ISSUE TITLE
Adapt header component

### ISSUE THREAD

**Issue by overeha** [code4romania/whos-who#2]
[Link to the UX specifications](https://www.figma.com/file/xdKbESSX397obRR5m9DMM5/CoVid---who-is-who)

Adapt the header from the already designed [componentes for the CoVid ecosystem. ](https://github.com/code4romania/taskforce-fe-components)

**The header will feature:** 
- project logo (it's in a [PR](https://github.com/code4romania/covid-assets/pull/8), will appear in covid-assets)
- Links to the other COVID-19 projects
- branding as shown below (using [this component](https://taskforce-fe-components.now.sh/?path=/story/developed-by--one-line-no-partners))

![header](https://user-images.githubusercontent.com/2820084/81534174-41eea300-9370-11ea-9061-6446104e8294.png)

**Comment by mihaela94** [comment]
Hello. As vrea sa iau eu issue-ul acesta.

**Comment by tudoramariei** [comment]
It's been assigned to you, @mihaela94 😄

**Comment by tudoramariei** [comment]
Since code4romania/taskforce-fe-components#113 was closed by code4romania/taskforce-fe-components#121 this issue has no more dependencies left

**Comment by mihaela94** [comment]
> Since [code4romania/taskforce-fe-components#113](https://github.com/code4romania/taskforce-fe-components/issues/113) was closed by [code4romania/taskforce-fe-components#121](https://github.com/code4romania/taskforce-fe-components/pull/121) this issue has no more dependencies left

As far as I know, we are still waiting for the logo to be done (haven't seen it in the covid-assets repo).

**Comment by tudoramariei** [comment]
True. I missed that one

**Comment by tudoramariei** [comment]
@mihaela94, would you have the time to finish this issue?

- The logo was added to https://github.com/code4romania/covid-assets and can be found as the `cineceface`/`cine-ce-face` files.
- Also, quite a few things have changed with the new version of the specifications, make sure you check the first comment and Page 2 of the specifications 😄
