### ISSUE TITLE
Change the `incubated-by` component in the footer

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/whos-who#21]
**DEPENDS ON:** code4romania/taskforce-fe-components#189

[Link to the UX specifications](https://www.figma.com/file/xdKbESSX397obRR5m9DMM5/CoVid---who-is-who?node-id=188%3A3)

The app footer should be updated to display the logo of our partner, Patria Bank.
This should use a new version of the `incubated-by` component from [taskforce-fe-components](https://taskforce-fe-components.now.sh/?path=/story/incubated-by--normal)
![image](https://user-images.githubusercontent.com/2820084/81533479-f4be0180-936e-11ea-87d5-ad277f5259ac.png)

**Comment by cipick** [comment]
i can take this!
