### ISSUE TITLE
Remove the About page

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/whos-who#22]
[Link to the UX specifications](https://www.figma.com/file/xdKbESSX397obRR5m9DMM5/CoVid---who-is-who?node-id=188%3A2)

The `About` page is no longer present in the UX specifications as the about section in the main page should be enough. The page along with its route (`/despre`) should be removed.

The reference to the page should be removed in #2

**Comment by kokosanki** [comment]
Hi, Can I work on this one?

**Comment by tudoramariei** [comment]
Sure!

**Comment by RaduCStefanescu** [comment]
Closed by #27
