### ISSUE TITLE
Update About section

### ISSUE THREAD

**Issue by overeha** [code4romania/whos-who#3]
[Link to the UX specifications](https://www.figma.com/file/xdKbESSX397obRR5m9DMM5/CoVid---who-is-who?node-id=188%3A3)

The about section will be displayed under the `Welcome` header in the website and will contain:
- the info about the project, found in the specs linked above
- a `mailto` link to `cineceface[at]code4.ro`

![image](https://user-images.githubusercontent.com/2820084/81532785-abb97d80-936d-11ea-82a0-3e72da626d4e.png)

**DEPRECATED:**
> The About page is composed of three areas: 
> - header
> - title & description
> - widgets area. (the Useful Instruments area should be displayed horizontally. Adapt already designed component from [here](https://github.com/code4romania/taskforce-fe-components))

**Comment by ionmosincat** [comment]
I could take this :)

**Comment by ionmosincat** [comment]
@overeha: do we have the description text?

**Comment by tudoramariei** [comment]
I was told there's a giant spreadsheet somewhere with the info we need. Until then you can take a look at other tasks as well, @ionmosincat 😃

**Comment by ionmosincat** [comment]
Ok, I'll look for another one then :)

**Comment by tudoramariei** [comment]
Adding a `dependency` tag until the content is available to have a better overview of all the issues

**Comment by RaduCStefanescu** [comment]
@ionmosincat please check out the initial issue, we added the Hero content and the text. Would you be able to continue with this issue?
Thank you!

**Comment by ionmosincat** [comment]
@RaduCStefanescu, sure thing, I'll take a look at it later today.

**Comment by ionmosincat** [comment]
@RaduCStefanescu, @aniri : could you please help me with this? 
Is there a way to pass an <a> tag inside the subtitle prop of the Hero component? (to have the email as link). I wasn't able to find a solution.

**Comment by catileptic** [comment]
I solved this, will add to @RaduCStefanescu's PR soon.

**Comment by catileptic** [comment]
Closing this since it's deprecated
