### ISSUE TITLE
Add frame for chart embed in homepage

### ISSUE THREAD

**Issue by overeha** [code4romania/whos-who#4]
[Link to the UX specifications](https://www.figma.com/file/xdKbESSX397obRR5m9DMM5/CoVid---who-is-who)

We will integrate a Flourish chart in the Homepage. 

- This chart will be displayed on the Homepage below the Page Title and Page hero text as shown below. 
- Chart height: 400px

![Homepage](https://user-images.githubusercontent.com/45068169/77807745-6ed14a00-7091-11ea-8e16-ca41e35b299b.png)

**Comment by teodoradima** [comment]
forgot to raise a hand first 🙋‍♀️
