### ISSUE TITLE
Add social sharing and embed options

### ISSUE THREAD

**Issue by overeha** [code4romania/whos-who#5]
1. Add sharing options for: 

- [x] Facebook
- [x] Twitter
- [x] Linkedin
- [ ] Instagram
- [ ] Embed (just for the Flourish chart)

2. All content elements should be shared separately. 
A user may share just a piece of content (an accordion box content) or the entire page or the chart. 
All content can be shared on social media, the chart needs to be embeddable also.

**Comment by aniri** [comment]
wireframes link https://www.figma.com/file/xdKbESSX397obRR5m9DMM5/CoVid---who-is-who?node-id=0%3A1

**Comment by tudoramariei** [comment]
This is done from the cemafac port. Closing

**Comment by tudoramariei** [comment]
Sorry, not everything is closed here, the chart still needs embedding

**Comment by moonflare** [comment]
> we don't have an Instagram redirect button

When we implemented this component we discovered there isn't a way of sharing content on Instagram in a similar way as on Facebook, for example.

**Comment by tudoramariei** [comment]
Right! Thanks for clarifying this, @moonflare! 
Closing this since _chart embedding_ has an issue of itself so this becomes a duplicate
