### ISSUE TITLE
Create accordion tabs for content

### ISSUE THREAD

**Issue by overeha** [code4romania/whos-who#7]
The content should be displayed in accordion tabs below titles. 
Each accordion will have
- a title area 
- a logo area (not mandatory)
- a text area

Each accordion content can be individually shared on social media as text with a link sending back to the site. 

![fb share](https://user-images.githubusercontent.com/45068169/77808212-1e5aec00-7093-11ea-8fbe-df6adf4ef80a.png)

See page here:
![Homepage](https://user-images.githubusercontent.com/45068169/77808232-2e72cb80-7093-11ea-9543-e5529f34b546.png)

**Comment by aniri** [comment]
related to https://github.com/code4romania/taskforce-fe-components/issues/108 and https://github.com/code4romania/taskforce-fe-components/issues/109

**Comment by alininayeh** [comment]
I can update the accordion component from the styleguide and apply it here

**Comment by tudoramariei** [comment]
Awesome! Assigning this to you, @alininayeh 
To have the issue from fe-components assigned to you, also leave a comment there, please 😄

**Comment by alininayeh** [comment]
The design of the component has been updated: https://github.com/alininayeh/whos-who/tree/7-create-accordion-tabs

Waiting for https://github.com/code4romania/taskforce-fe-components/issues/109 to be done, so I can check that everything works fine and create a pull request.

**Comment by tudoramariei** [comment]
Adding a `dependency` label to better see that this still depends on `fe-components`
Also, when code4romania/taskforce-fe-components#109 is ready, having some `Lorem ipsum` together with most of the organisations should be enough to close this

More details on the organisations can be found [here](https://github.com/code4romania/whos-who/issues/17#issuecomment-605455737) but the complete list with descriptions is not available yet

**Comment by tudoramariei** [comment]
Hey, @alininayeh! Would you be able to continue working on this? 😄  
I discussed with @moonflare and right now, code4romania/taskforce-fe-components#109 will not be implemented since it's so time-consuming. 
The slugs and routing functionality should be implemented in the project, the component won't be handling this.
If I missed something, Dan can correct me.

**Comment by alininayeh** [comment]
Hey. I will work on this these days. This weekend I will be busy, but I will work during the weekdays

**Comment by tudoramariei** [comment]
Hey, @alininayeh! We'll have to deliver this project by tomorrow so I'm going to add the content to the accordions. I'll be creating a new issue in a bit in which we can look over more advanced features for accordions (besides the content).
