### ISSUE TITLE
Adapt sidebar from component

### ISSUE THREAD

**Issue by overeha** [code4romania/whos-who#8]
The webpage should feature a sidebar with useful instruments as shown in the page below. 
The Useful Instrument sidebar will feature:
- box for Chrome Add-on
- box for Firefox Add-on
- box for Stiri Oficiale
- box for Cetrebuiesafac
- box for Datelazi

please find the sidebar component [here](https://github.com/code4romania/taskforce-fe-components). 
![Homepage](https://user-images.githubusercontent.com/45068169/77808308-785bb180-7093-11ea-8508-8045c3a1d539.png)

**Comment by teodoradima** [comment]
🙋‍♀️

**Comment by tudoramariei** [comment]
Hey, @teodoradima, sorry for the duplicate work but it seems like this is also done
