### ISSUE TITLE
Add newsletter component below sidebar

### ISSUE THREAD

**Issue by overeha** [code4romania/whos-who#9]
Below the sidebar, there should be a newsletter subscription area. 
Please use the same component as found in the[ components repo.](https://github.com/code4romania/taskforce-fe-components)

**Comment by teodoradima** [comment]
🙋‍♀️

**Comment by tudoramariei** [comment]
Very well, then

**Comment by tudoramariei** [comment]
Closing since it's implemented from porting cemafac
